name: Main workflow

on:
  pull_request:
  push:
  # Prime the caches every Monday
  schedule:
    - cron: "14 3 * * MON"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.08.1
          - 4.05.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Check type
        run: yarn typecheck

      - name: Ensure dist directory is up-to-date
        if: runner.os == 'Linux'
        shell: bash
        run: |
          yarn build
          if [ "$(git status dist --porcelain | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

      - name: Generate date-based cache key
        id: key
        run: |
          # Put year and week number in steps.key.outputs.week
          # This command "works" for both PowerShell and POSIX shell
          echo ":$(Write-Output ':')set-output name=week::$(Get-Date -UFormat '%Y-%W')-"
          echo ":`echo :`set-output name=week::`date -u '+%Y-%W'`-"

      - name: opam Cache
        uses: actions/cache@v2
        with:
          path: .github/caches/opam
          key: ${{ runner.os }}-${{ steps.key.outputs.week }}1

      - name: compiler Cache
        uses: actions/cache@v2
        with:
          path: .github/caches/compiler
          key:
            ${{ runner.os }}-${{ matrix.ocaml-version }}-${{
            steps.key.outputs.week }}1

      - name: build Cache
        uses: actions/cache@v2
        with:
          path: .github/caches/build
          key:
            ${{ runner.os }}-${{ matrix.ocaml-version }}-${{
            steps.key.outputs.week }}1-build

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ./
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam depext yaml --install --yes

      - name: Check formatting
        run: yarn fmt:check
        if: always()

      - name: Check lint
        run: yarn lint
        if: always()
